FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
RUN apt install bind9 bind9utils net-tools dnsutils -y
RUN apt-get install -y nano
RUN apt install iputils-ping -y


WORKDIR /etc/bind

COPY named.conf /etc/bind/named.conf
COPY woody.intra /etc/bind/woody.intra

RUN mkdir /var/log/named
RUN chown bind:bind /var/log/named
RUN touch /var/log/named/misc.log /var/log/named/query.log
RUN chown bind:bind /var/log/named/*

EXPOSE 53/udp 53/tcp



